_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  ROI_HEADS:
    NAME: "OpenSetStandardROIHeads"
    NUM_CLASSES: 81
    NUM_KNOWN_CLASSES: 20
  ROI_BOX_HEAD:
    NAME: "FastRCNNSeparateConvFCHead"
    OUTPUT_LAYERS: "OpenDetFastRCNNOutputLayers"
    CLS_AGNOSTIC_BBOX_REG: True
UPLOSS:
  START_ITER: 100
  SAMPLING_METRIC: "min_score"
  TOPK: 3
  ALPHA: 1.0
  WEIGHT: 1.0
ICLOSS:
  OUT_DIM: 128
  QUEUE_SIZE: 256
  IN_QUEUE_SIZE: 16
  BATCH_IOU_THRESH: 0.5
  QUEUE_IOU_THRESH: 0.7
  TEMPERATURE: 0.1
  WEIGHT: 0.1